billing_system2/urls.py
#from django.conf.urls import url, include
from django.urls import include, re_path
from django.contrib import admin

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'index/', include('bills.urls'))
]

bills/urls.py
#from django.conf.urls import url
from django.urls import re_path

from . import views

app_name = 'bill'

urlpatterns = [
    re_path(r'^$',views.index,name='index'),
    re_path(r'^bill/',views.cal_amount,name='cal_amount'),
]

bills/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.six import python_2_unicode_compatible
from django.db import models
# Create your models here.

@python_2_unicode_compatible
class Customer(models.Model):
    customer_id = models.AutoField(primary_key=True)
    customer_name = models.CharField(max_length=200,default="")
    customer_mob_no = models.CharField(max_length=200,default="")
    customer_idt =  models.CharField(max_length=7,default="")	

    def __str__(self):
        return self.customer_name

@python_2_unicode_compatible
class Product(models.Model):
	product_id = models.AutoField(primary_key=True)
	product_name = models.CharField(max_length=200)
	product_detail = models.CharField(max_length=200)
	product_code = models.CharField(max_length=4,default='0000')
	product_qlt1_price = models.DecimalField(max_digits=6, decimal_places=2,default=0.00)
	product_qlt2_price = models.DecimalField(max_digits=6, decimal_places=2,default=0.00)
	product_qlt3_price = models.DecimalField(max_digits=6, decimal_places=2,default=0.00)
	
	def __str__(self):
		return self.product_name

bills/forms.py
from django import forms
from django.contrib.auth import get_user_model

class InfoForm(forms.Form):
    customername = forms.CharField(widget=forms.TextInput(
			attrs={"class":"form-control",
			"placeholder":"Customer Name",
			'name': 'display_name'
			}
			))

    customerid = forms.CharField(widget=forms.TextInput(
			attrs={"class":"form-control",
			"placeholder":"Customer ID",
			'name': 'display_name'
			}
			),required=False)
	
    mobilenumber = forms.CharField(widget=forms.TextInput(
        attrs={"class": "form-control",
               "placeholder": "Your Mobile Number"
               }
    ))

bills/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.forms.utils import ErrorDict

from django.shortcuts import render
from .forms import InfoForm
from .models import Customer, Product


# Create your views here.

def index(request):
    form = InfoForm(request.POST or None)

    customername = request.POST.get('customername')
    mobilenumber = request.POST.get('mobilenumber')
    customerid = request.POST.get('customerid')

    #Check if the customer is existing in database

    print('Searching for customer',customerid) 

    try:
        customer = Customer.objects.get(customer_idt=customerid)
        print('cust present') 
        request.session['isNew'] = False
    except Customer.DoesNotExist as e:   
        print('cust not present') 
        request.session['isNew'] = True
        if form.is_valid():
            print('for is valid') 
            cus = Customer(customer_name=customername,customer_mob_no=mobilenumber,customer_idt=customerid)
            cus.save()
            print(form.cleaned_data)



    product = Product.objects.all()
    product_no = Product.objects.all().count()     
    mylist = []
    # db store
    context = {
        'title': 'VIT Billing System',
        'Name': customername,
        'mobilenumber': mobilenumber,
        'products':product,
        'product_no':product_no,
        'mylist':mylist
    }

    if request.method == "POST" and customerid != None:
        return render(request, "bills/menu.html", context)

    return render(request, "bills/index.html", {'form': form, 'title': 'VIT Billing System'})


def cal_amount(request):
    print("cal_amount")
    amount = 0.0
    count = 0

    isNew = False

    if(request.session['isNew']):
        request.session['isNew'] = False
        isNew = True
    else:
        isNew = False

    print('========== Is Customer New ? :',isNew)

    username = request.POST.get('username')
    mobilenumber = request.POST.get('mobilenumber')

    products = Product.objects.all()
    total_count = Product.objects.all().count()
    for p in products:
        id = p.product_id
        q = request.POST.get('q_id_' + str(id))
        qly = request.POST.get('qlt_id_' + str(id))

        qlt_price = 0.0;
        if(qly == '1'):
            qlt_price = p.product_qlt1_price
        if(qly == '2'):
            qlt_price = p.product_qlt2_price
        if(qly == '3'):
            qlt_price = p.product_qlt3_price
       

        if q is not None and q != '' and float(q):
            q = float(q)
            amount += q * float(qlt_price)
            count += 1

        discount = 0.0
        cashdiscount = 0.0
        final_amount = amount

        if amount > 10000 :
            discount = (amount*0.01)
            final_amount = amount - discount
            if (isNew != True):
                cashdiscount = (amount*0.012)

    context = {
        'count': count,
        'amount': amount,
        'discount': discount,
        'final_amount':final_amount,
        'cash_discount':cashdiscount
    }

    return render(request, "bills/bills.html", context)

bills/templates/bills/bills.html
TOTAL ITEMS {{ count }}<br>
TOTAL AMOUNT {{ amount }}<br>
TOTAL DISCOUNT {{ discount }}<br>
TOTAL FINAL AMOUNT {{ final_amount }}<br>
CASH DISCOUNT {{ cash_discount }}<br>
<br>
Thank You

bills/templates/bills/index.html
<!doctype html>
	<html lang="en">
	  <head>
	    <!-- Required meta tags -->
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	    <!-- Bootstrap CSS -->
	    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

	    <title>VIT Billing System</title>
	  </head>
	  <body>
      <center><h1>{{ title }}</h1></center>
	  <div class='container'>
	  	<div class='row'>
	  		<div class='col'>
	  			<div class='col-sm-6 col-sm-12'>
	 				<form method='POST'>
	 					{% csrf_token %}
	 					{{ form }}
	 					<br><button type="submit" class="btn btn-primary">Submit</button>
	  				</form>
	  			</div>
	  		</div>
	  	</div>
	  </div>
	    <!-- Optional JavaScript -->
	    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
	    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
	  </body>
	</html>

bills/templates/bills/menu.html
{% load keyy %}
<!doctype html>
	<html lang="en">
	  <head>
	    <!-- Required meta tags -->
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	    <!-- Bootstrap CSS -->
	    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

	    <title>Menu</title>
	  </head>
	  <body>
      <center><h1>{{ title }}</h1></center>
	  <center>
      <div class='container'>
	  	<div class='row'>
	  		<div class='col'>
	  			<div class='col-sm-6 col-sm-12'>
                    <h3>Menu Options</h3>
                    Name:{{ Name }}<br>
                    Mob.No:{{ mobilenumber }}

	 				<form method='POST' action="{% url 'bill:cal_amount' %}" name= 'myform'>
	 					{% csrf_token %}
                        <input type="hidden" name="name" value="{{ Name }}">
                        <input type="hidden" name="mobilenumber" value="{{ mobilenumber }}">
                        <table>
                            <tr>
								<th>Item-code</th>&nbsp
                                <th>Items-Name</th>&nbsp
                                <th><center>Quantity</center></th>&nbsp
								<th><center>Qlty</center></th>&nbsp
								<th><center>Qlt1Price</center></th>
								<th><center>Qlt2Price</center></th>
								<th><center>Qlt3Price</center></th>
                            </tr>
                            {{ product.count }}
                            {% for p in products %}
                                <tr>
								<td>{{ p.product_code }}</td>&nbsp
                                <td>{{ p.product_name }}</td>&nbsp
                                <td><input type="number" min="0" value="0" step="any" name="q_id_{{ p.product_id }}"></td>&nbsp
								<td>
									<select name="qlt_id_{{ p.product_id }}" id="qly">
										<option value="1">1</option>
										<option value="2">2</option>
										<option value="3">3</option>
									</select>
								</td>
								<td><center>{{ p.product_qlt1_price }}</center></td>
								<td><center>{{ p.product_qlt2_price }}</center></td>
								<td><center>{{ p.product_qlt3_price }}</center></td>
                                </tr>
                            {% endfor %}                            
                        </table>
	 					<br><button type="submit" class="btn btn-primary">Submit</button>
	  				</form>
	  			</div>
	  		</div>
	  	</div>
	  </div>
      </center>
	    <!-- Optional JavaScript -->
	    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
	    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
	  </body>
	  <script type="text/javascript">
	  	function submitform()
	  	{
	  	var formData = JSON.stringify($("#myform").serializeArray());
	  	console.log(formData)
	  	}
	  </script>
	</html>